---
- name: install nginx
  apt:
    name: nginx
    state: present

- name: create nginx user
  user:
    name: nginx
    shell: /usr/sbin/nologin

- name: deploy nginx config
  copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: enable and test nginx config 
  shell: |-
    sudo nginx -t &&
      sudo systemctl enable nginx &&
      sudo systemctl restart nginx
